// AUTO-GENERATED by scripts/sync-logos.mjs – 勿手动编辑
// 数据来源: Artificial Analysis 官网公开 logo 资源
export interface CreatorLogoInfo {
  file: string
  name: string
}

export const CREATOR_LOGOS: Record<string, CreatorLogoInfo> = {
  "openai": {
    "file": "/img/logos/openai_small.svg",
    "name": "OpenAI"
  },
  "xai": {
    "file": "/img/logos/spacexai.svg",
    "name": "SpaceXAI"
  },
  "meta": {
    "file": "/img/logos/meta_small.svg",
    "name": "Meta"
  },
  "google": {
    "file": "/img/logos/google_small.svg",
    "name": "Google"
  },
  "anthropic": {
    "file": "/img/logos/anthropic_small.svg",
    "name": "Anthropic"
  },
  "mistral": {
    "file": "/img/logos/mistral_small.png",
    "name": "Mistral"
  },
  "deepseek": {
    "file": "/img/logos/deepseek_small.svg",
    "name": "DeepSeek"
  },
  "perplexity": {
    "file": "/img/logos/perplexity_small.png",
    "name": "Perplexity"
  },
  "tii-uae": {
    "file": "/img/logos/tii_small.svg",
    "name": "TII UAE"
  },
  "aws": {
    "file": "/img/logos/aws_small.svg",
    "name": "Amazon"
  },
  "azure": {
    "file": "/img/logos/microsoft_small.svg",
    "name": "Microsoft"
  },
  "liquidai": {
    "file": "/img/logos/liquidai_small.svg",
    "name": "Liquid AI"
  },
  "upstage": {
    "file": "/img/logos/upstage_small.svg",
    "name": "Upstage"
  },
  "alibaba": {
    "file": "/img/logos/alibaba_small.svg",
    "name": "Alibaba"
  },
  "minimax": {
    "file": "/img/logos/minimax_small.svg",
    "name": "MiniMax"
  },
  "nvidia": {
    "file": "/img/logos/nvidia_small.svg",
    "name": "NVIDIA"
  },
  "kimi": {
    "file": "/img/logos/kimi.jpg",
    "name": "Kimi"
  },
  "stepfun": {
    "file": "/img/logos/stepfun_small.svg",
    "name": "StepFun"
  },
  "ai2": {
    "file": "/img/logos/ai2_small.svg",
    "name": "Allen Institute for AI"
  },
  "ibm": {
    "file": "/img/logos/ibm_small.svg",
    "name": "IBM"
  },
  "inception": {
    "file": "/img/logos/inceptionlabs_small.svg",
    "name": "Inception"
  },
  "reka-ai": {
    "file": "/img/logos/reka_small.svg",
    "name": "Reka AI"
  },
  "nous-research": {
    "file": "/img/logos/nousresearch_small.jpg",
    "name": "Nous Research"
  },
  "lg": {
    "file": "/img/logos/lg_small.png",
    "name": "LG AI Research"
  },
  "xiaomi": {
    "file": "/img/logos/xiaomi_small.svg",
    "name": "Xiaomi"
  },
  "baidu": {
    "file": "/img/logos/baidu_small.svg",
    "name": "Baidu"
  },
  "sarvam": {
    "file": "/img/logos/sarvam.svg",
    "name": "Sarvam"
  },
  "multiversecomputing": {
    "file": "/img/logos/multiversecomputing_small.svg",
    "name": "Multiverse Computing"
  },
  "deepcogito": {
    "file": "/img/logos/deepcogito_small.png",
    "name": "Deep Cogito"
  },
  "tencent": {
    "file": "/img/logos/tencent_small.svg",
    "name": "Tencent"
  },
  "kwaikat": {
    "file": "/img/logos/kwaikat_small.svg",
    "name": "KwaiKAT"
  },
  "prime-intellect": {
    "file": "/img/logos/prime-intellect_small.svg",
    "name": "Prime Intellect"
  },
  "motif-technologies": {
    "file": "/img/logos/motif_small.svg",
    "name": "Motif Technologies"
  },
  "mbzuai": {
    "file": "/img/logos/mbzuai_small.svg",
    "name": "MBZUAI Institute of Foundation Models"
  },
  "korea-telecom": {
    "file": "/img/logos/korea-telecom_small.png",
    "name": "Korea Telecom"
  },
  "naver": {
    "file": "/img/logos/naver_small.webp",
    "name": "Naver"
  },
  "longcat": {
    "file": "/img/logos/longcat_small.svg",
    "name": "LongCat"
  },
  "trillionlabs": {
    "file": "/img/logos/trillionlabs_small.svg",
    "name": "Trillion Labs"
  },
  "nanbeige": {
    "file": "/img/logos/nanbeige_small.png",
    "name": "Nanbeige"
  },
  "swiss-ai-initiative": {
    "file": "/img/logos/swiss-ai-initiative_small.png",
    "name": "Swiss AI Initiative"
  },
  "openbmb": {
    "file": "/img/logos/openbmb_small.svg",
    "name": "OpenBMB"
  },
  "arcee": {
    "file": "/img/logos/arcee_small.svg",
    "name": "Arcee AI"
  },
  "china-mobile": {
    "file": "/img/logos/china_mobile_small.png",
    "name": "China Mobile"
  },
  "nex": {
    "file": "/img/logos/nex_small.svg",
    "name": "Nex AGI"
  },
  "thinking-machines": {
    "file": "/img/logos/thinking_machines.svg",
    "name": "Thinking Machines"
  },
  "ai9star": {
    "file": "/img/logos/ai9stars.svg",
    "name": "AI9Stars"
  },
  "zai": {
    "file": "/img/logos/zai_small.svg",
    "name": "Z AI"
  },
  "cohere": {
    "file": "/img/logos/cohere_small.svg",
    "name": "Cohere"
  },
  "servicenow": {
    "file": "/img/logos/servicenow_small.svg",
    "name": "ServiceNow"
  },
  "ai21-labs": {
    "file": "/img/logos/ai21_small.svg",
    "name": "AI21 Labs"
  },
  "inclusionai": {
    "file": "/img/logos/inclusionai_small.jpg",
    "name": "InclusionAI"
  },
  "bytedance_seed": {
    "file": "/img/logos/bytedance_small.svg",
    "name": "ByteDance Seed"
  },
  "agnes-ai": {
    "file": "/img/logos/sapiens.svg",
    "name": "Sapiens AI"
  },
  "celeris": {
    "file": "/img/logos/celeris.svg",
    "name": "Celeris"
  },
  "openchat": {
    "file": "/img/logos/openchat_small.png",
    "name": "OpenChat"
  },
  "databricks": {
    "file": "/img/logos/databricks_small.png",
    "name": "Databricks"
  },
  "snowflake": {
    "file": "/img/logos/snowflake_small.svg",
    "name": "Snowflake"
  }
}
