// 从 Artificial Analysis 官网同步各模型开发商的 logo 到 public/img/logos/
// 并生成 src/lib/logos.ts（前端展示用映射）。
// 用法: node scripts/sync-logos.mjs
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const SNAPSHOT_DIR = join(ROOT, "data", "snapshot")
const LOGOS_DIR = join(ROOT, "public", "img", "logos")
const OUT_TYPES = join(ROOT, "src", "lib", "logos.ts")
const BASE = "https://artificialanalysis.ai/img/logos"

const LS = { svg: "image/svg+xml", png: "image/png", webp: "image/webp", jpg: "image/jpeg", jpeg: "image/jpeg" }

// 官方 CDN 里与 creator slug 不一致的品牌名（slug -> 实际文件基名）
const ALIASES = {
  "tii-uae": "tii",
  azure: "microsoft",
  "inception": "inceptionlabs",
  "reka-ai": "reka",
  "nous-research": "nousresearch",
  "motif-technologies": "motif",
  "china-mobile": "china_mobile",
  "ai9star": "ai9stars",
  "ai21-labs": "ai21",
  "bytedance_seed": "bytedance",
  "agnes-ai": "sapiens",
  "lg": "lg",
  "xai": "spacexai",
}

// 候选文件基名（先带 _small 后缀，再不带）
function candidates(slug) {
  const names = [slug, slug.replace(/-/g, "_"), ALIASES[slug]].filter(Boolean)
  const out = []
  for (const n of names) {
    out.push(`${n}_small`, n)
  }
  return [...new Set(out)]
}

async function fetchBuffer(url, timeoutMs = 20000) {
  const ctrl = new AbortController()
  const timer = setTimeout(() => ctrl.abort(), timeoutMs)
  try {
    const res = await fetch(url, { signal: ctrl.signal, headers: { "user-agent": "modelrank-logosync/1.0" } })
    if (!res.ok) return null
    return Buffer.from(await res.arrayBuffer())
  } catch {
    return null
  } finally {
    clearTimeout(timer)
  }
}

function loadSnapshots() {
  const creators = new Map() // slug -> name
  const files = ["models.json", "text-to-image.json", "text-to-video.json", "image-to-video.json", "text-to-speech.json"]
  for (const f of files) {
    const path = join(SNAPSHOT_DIR, f)
    if (!existsSync(path)) continue
    let raw = null
    try { raw = JSON.parse(readFileSync(path, "utf-8")) } catch { continue }
    for (const m of raw?.data ?? []) {
      const c = m.model_creator
      if (c?.slug && !creators.has(c.slug)) creators.set(c.slug, c.name ?? c.slug)
    }
  }
  return creators
}

async function main() {
  mkdirSync(LOGOS_DIR, { recursive: true })
  const creators = loadSnapshots()
  if (!creators.size) {
    console.log("[logos] no snapshot data, skip")
    return
  }
  const map = {} // slug -> { file, ext }
  const missing = []
  let ok = 0
  for (const [slug, name] of creators) {
    const cands = candidates(slug)
    let found = null
    for (const base of cands) {
      for (const ext of Object.keys(LS)) {
        const path = `${base}.${ext}`
        const local = join(LOGOS_DIR, path)
        if (existsSync(local) && !process.env.FORCE) {
          found = { file: path, ext }
          break
        }
        const buf = await fetchBuffer(`${BASE}/${path}`)
        if (buf) {
          writeFileSync(local, buf)
          found = { file: path, ext }
          break
        }
      }
      if (found) break
    }
    if (found && found.file) {
      map[slug] = { file: `/img/logos/${found.file}`, name }
      ok++
    } else {
      missing.push(slug)
      console.log(`[logos] MISS  ${slug} (${name})`)
    }
  }

  const code = `// AUTO-GENERATED by scripts/sync-logos.mjs – 勿手动编辑\n` +
    `// 数据来源: Artificial Analysis 官网公开 logo 资源\n` +
    `export interface CreatorLogoInfo {\n  file: string\n  name: string\n}\n\n` +
    `export const CREATOR_LOGOS: Record<string, CreatorLogoInfo> = ${JSON.stringify(map, null, 2)}\n`
  writeFileSync(OUT_TYPES, code)

  console.log(`[logos] done: ${ok}/${creators.size} logos, missing: ${missing.join(", ") || "无"}`)
}

main().catch((e) => { console.error("[logos] fatal:", e); process.exit(1) })